[project]
name = "scalelock"
version = "2026.1.0"
description = ""
authors = [{ name = "Dragon Security Team", email = "hello@dragonsecurity.io" }]
requires-python = "==3.13.*"
dependencies = [
    "Django==6.0",
    "defusedxml==0.7.1",
    "cryptography==46.0.4",
]